// generated by Fast Light User Interface Designer (fluid) version 1.0400

#ifndef FunctionGraphWindow_h
#define FunctionGraphWindow_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>

class FunctionGraphWindow: public Fl_Double_Window
{
public:
  FunctionGraphWindow(double (*f)(double));
  void draw();
  int handle(int e);
  struct Pixel
  {
    int x, y;
  };
private:
  double xLeft = 1;
  double xRight = 3;
  double yLow = -3;
  double yHigh = -1;
  void drawXyAxis();
  void drawXUnitInterval();
  //void drawYUnitInterval();
  Pixel getOrigin();
  bool isYAxisInUpperHalf();
  //void drawFunction();
};
#endif
