// generated by Fast Light User Interface Designer (fluid) version 1.0400

#ifndef FunctionGraphWindow_h
#define FunctionGraphWindow_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>

class FunctionGraphWindow: public Fl_Double_Window
{
public:
  FunctionGraphWindow(double (*f)(double));
  void draw();
  struct Pixel
  {
    int x, y;
  };
private:
  double xLeft = -3;
  double xRight = 1;
  double yLow = 1;
  double yHigh = 2;
  void drawXyAxis();
  void drawUnitInterval();
  Pixel getOrigin();
  //void drawFunction();
};
#endif
